### ISSUE TITLE
Some questions in section 3.1  of paper "pcoxtime"

### ISSUE THREAD

**Issue by quinn-lee-congyue** [CYGUBICKO/pcoxtime-pkg#1]
**I run the code in Section 3.1 of this paper, but the result is not consistent with the result in your paper.**

```
library("ahaz")
data("sorlie",package="ahaz")
dat <- sorlie
dim(dat) #115*551
```

> [1] 115 551

```
cv_fit1 <- pcoxtimecv(Surv(time, status)~., data = dat,
+                       alphas = c(0.4, 0.5), lambdas = NULL,  devtype = "vv",
+                       lamfract = 0.6, refit = TRUE, nclusters = 4)
```

> Progress: cross-validating ====> alpha =  0.4 
> Progress: cross-validating ====> alpha =  0.5 
> Progress: Refitting with optimal lambdas... 

`print(cv_fit1)`

> Call:
> pcoxtimecv(formula = Surv(time, status) ~ ., data = dat, alphas = c(0.4, 
>     0.5), lambdas = NULL, lamfract = 0.6, devtype = "vv", refit = TRUE, 
>     nclusters = 4)
> 
> Optimal parameter values
>  lambda.min lambda.1se alpha.optimal
>   0.6670488  0.6670488           0.4

**Comment by CYGUBICKO** [comment]
Once you run the example, can you copy and paste the result of `sessionInfo()` here?

**Comment by quinn-lee-congyue** [comment]
**Here is the result :**
`sessionInfo(package = "pcoxtime")`

> R version 4.0.3 (2020-10-10)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Big Sur 10.16
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> character(0)
> 
> other attached packages:
> [1] pcoxtime_1.0
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.6                mvtnorm_1.1-1            
>  [3] lattice_0.20-41           zoo_1.8-8                
>  [5] png_0.1-7                 glmnet_4.1-1             
>  [7] digest_0.6.27             foreach_1.5.1            
>  [9] R6_2.5.0                  backports_1.2.1          
> [11] PermAlgo_1.1              MatrixModels_0.4-1       
> [13] ggplot2_3.3.3             riskRegression_2020.12.08
> [15] pillar_1.4.7              utils_4.0.3              
> [17] rlang_0.4.10              multcomp_1.4-16          
> [19] rstudioapi_0.13           data.table_1.13.6        
> [21] SparseM_1.78              rpart_4.1-15             
> [23] Matrix_1.2-18             checkmate_2.0.0          
> [25] splines_4.0.3             stringr_1.4.0            
> [27] foreign_0.8-80            htmlwidgets_1.5.3        
> [29] munsell_0.5.0             compiler_4.0.3           
> [31] numDeriv_2016.8-1.1       xfun_0.21                
> [33] pkgconfig_2.0.3           stats_4.0.3              
> [35] base64enc_0.1-3           shape_1.4.5              
> [37] htmltools_0.5.1.1         nnet_7.3-14              
> [39] tidyselect_1.1.0          tibble_3.0.6             
> [41] gridExtra_2.3             htmlTable_2.1.0          
> [43] prodlim_2019.11.13        matrixStats_0.58.0       
> [45] Hmisc_4.5-0               rms_6.1-1                
> [47] codetools_0.2-16          grDevices_4.0.3          
> [49] crayon_1.4.1              dplyr_1.0.4              
> [51] conquer_1.0.2             MASS_7.3-53              
> [53] timereg_1.9.8             grid_4.0.3               
> [55] polspline_1.1.19          nlme_3.1-149             
> [57] gtable_0.3.0              lifecycle_1.0.0          
> [59] magrittr_2.0.1            datasets_4.0.3           
> [61] scales_1.1.1              stringi_1.5.3            
> [63] RcppArmadillo_0.10.2.1.0  doParallel_1.0.16        
> [65] latticeExtra_0.6-29       ellipsis_0.3.1           
> [67] graphics_4.0.3            generics_0.1.0           
> [69] vctrs_0.3.6               sandwich_3.0-0           
> [71] TH.data_1.0-10            base_4.0.3               
> [73] Formula_1.2-4             lava_1.6.9               
> [75] RColorBrewer_1.1-2        iterators_1.0.13         
> [77] tools_4.0.3               cmprsk_2.2-10            
> [79] glue_1.4.2                purrr_0.3.4              
> [81] mets_1.2.8.1              jpeg_0.1-8.1             
> [83] parallel_4.0.3            survival_3.2-7           
> [85] colorspace_2.0-0          cluster_2.1.0            
> [87] knitr_1.31                methods_4.0.3            
> [89] quantreg_5.83

**Comment by CYGUBICKO** [comment]
Thanks. The problem is due to BLAS/LAPACK libraries, though I am not sure why this should be a problem. A quick fix for now is to install Install `OpenBLAS` and `AtlasBLAS` in your system then set it as the default for matrix product. I will try and figure out better ways to fix this. But if you want to try it out, this is the process:

Go to terminal then type
`sudo apt-get install libopenblas-base libatlas3-base`
`sudo update-alternatives --config liblapack.so.3-x86_64-linux-gnu`

Then select the option which ends with `liblapack.so.3`, if not default.

Now if you run `sessionInfo()` in `R` console, you should see something like
```
Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
```
You can rerun the example and see it gives you the same result.

**Comment by quinn-lee-congyue** [comment]
Thinks！I know what you mean.There are no **apt-get** command on the Mac, so I tried the R help document command as follows
```
cd /Library/Frameworks/R.framework/Resources/lib
ln -sf libRblas.vecLib.dylib libRblas.dylib
```
But the result did never change
`sessionInfo()`

> R version 4.0.4 (2021-02-15)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Big Sur 10.16
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

But I've seen someone's results in google like this

> Matrix products: default
> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

I also found the file **libRblas.dylib** in my path **/Library/Frameworks/R.framework/Versions/4.0/Resources/lib**,but I don't know how to set this file to Matrix Products by default.

**Comment by CYGUBICKO** [comment]
Thanks! I don't recommend this as the best solution, so proceed at your own discretion...
To switch Apple’s BLAS:

```
cd /Library/Frameworks/R.framework/Resources/lib
ln -sf /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current/libBLAS.dylib libRblas.dylib
```

You can verify by running `sessionInfo()`, and expect something like:

```
Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
```

Use `ln -sf libRblas.0.dylib libRblas.dylib` to revert back to default.

**Comment by quinn-lee-congyue** [comment]
Thank you for your help and patience.Yesterday I typed `sessionInfo()` on both my classmate's Mac and Windows computers, but the result was the same as mine, even only 

> Matrix products: default

on windows.
I wonder if this is the reason for the latest R or computer systems？

**Here's some information in my folder**
```
localhost:~ licongyue$ cd /Library/Frameworks/R.framework/Resources/lib
localhost:lib licongyue$ ls
libR.dylib              libRblas.dylib.dSYM     libgcc_s.1.dylib
libR.dylib.dSYM         libRlapack.dylib        libgfortran.5.dylib
libRblas.dylib          libRlapack.dylib.dSYM   libquadmath.0.dylib
```
**and**
```
licongyue@localhost ~ % cd /System/Library/Frameworks/Accelerate.framework/Frameworks
licongyue@localhost Frameworks % ls
vImage.framework	vecLib.framework
licongyue@localhost vecLib.framework % ls
Resources	Versions	libBigNum.dylib
licongyue@localhost vImage.framework % ls
Resources	Versions
```

**Here is some information from R's official website**

> https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html#Which-BLAS-is-used-and-how-can-it-be-changed_003f

But it didn't work.

**Comment by CYGUBICKO** [comment]
I am still working on a permanent fix to the problem and thanks for sharing the link. 
I will try and get Mac OS computer to troubleshoot by myself.  

The problem is the default algebra library (BLAS) used in the system. I changed my to something similar to yours and I manage to get different results. But with linux, I am able to easily configure it to use the R friendly BLAS.
An alternative now is to run your code in linux system.

I will come back to this issue once I find a working solution. But for now, you can directly contact me through email on the pcoxtime paper, I will be glad to assist.

**Comment by CYGUBICKO** [comment]
I tried `pcoxtime` on Mac OS with the same setup as yours and it gives consistent results. I suspect there could be some conflict between BLAS libraries in your system which at this point I cannot tell. Here is the example:

```
> set.seed(123407)
> sim <- simtdc()
> df <- sim$data
> vnames <- colnames(df)[!colnames(df) %in% c("Id", "Fup")]
> df <- df[ ,vnames]
> # Estimate coefficients using coxph
> mod <- pcoxtime(Surv(Start, Stop, Event) ~ ., df, lambda = 0)
Model converged after 12 iterations
> mod
Call:
pcoxtime(formula = Surv(Start, Stop, Event) ~ ., data = df, lambda = 0)

           coef exp(coef)
xtf1  0.5274756 1.6946490
xtf2 -0.3412437 0.7108856
xtd1 -0.1705186 0.8432274
xtd2  0.2212850 1.2476790
4 out of 4 coefficients are nonzero
n = 5563 , number of events = 80
> mod_coxph <- coxph(Surv(Start, Stop, Event) ~ ., df)
> mod_coxph
Call:
coxph(formula = Surv(Start, Stop, Event) ~ ., data = df)

        coef exp(coef) se(coef)      z        p
xtf1  0.5303    1.6995   0.1380  3.844 0.000121
xtf2 -0.3434    0.7093   0.1069 -3.213 0.001315
xtd1 -0.1692    0.8443   0.1140 -1.484 0.137776
xtd2  0.2237    1.2507   0.1153  1.939 0.052474


> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
```

**Comment by quinn-lee-congyue** [comment]
Thank you very much！I've learned a lot from you.The code I just ran you above is consistent.Your paper is very clear and beautiful.good job.
